{
 "title": "Consul Client",
 "tags": [ "consul" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_service_info{service=~\".*consul.*server\"}, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(consul_raft_state_leader{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "agent",
    "label": "agent",
    "query": "label_values(consul_client_rpc{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "server",
    "label": "Consul Server",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_kind=\"StatefulSet\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Client ACL Blocked Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a deregistration fails for a service (blocked by an ACL)\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_acl_blocked_service_registration{namespace=~\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client RPC Request Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent in client mode makes an RPC request to a Consul server. This gives a measure of how much a given agent is loading the Consul servers. Currently, this is only generated by agents in client mode, not Consul servers.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_rpc{namespace=~\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client RPC Exceeded Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent in client mode makes an RPC request to a Consul server gets rate limited by that agent's limits configuration. This gives an indication that there's an abusive application making too many requests on the agent, or that the rate limit needs to be increased. Currently, this only applies to agents in client mode, not Consul servers.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_rpc_exceeded{namespace=~\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client RPC Failed Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent in client mode makes an RPC request to a Consul server and fails.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_rpc_failed{namespace=~\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client API Catalog Register Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent receives a catalog register request.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_api_catalog_register{namespace=~\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client API Success Catalog Register Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent successfully responds to a catalog register request.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_api_success_catalog_register{namespace=~\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client RPC Error Catalog Register Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent receives an RPC error for a catalog register request.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_rpc_error_catalog_register{namespace=~\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client API Error Catalog Deregister Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent receives a catalog de-register request.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_api_catalog_deregister{namespace=~\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client RPC Error Catalog Deregister Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent receives an RPC error for a catalog de-register request.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_rpc_error_catalog_deregister{namespace=~\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client API Catalog Datacenter Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent receives a request to list datacenters in the catalog.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_api_catalog_datacenters{namespace=~\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client API Success Catalog Datacenter Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent successfully responds to a request to list datacenters.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_api_success_catalog_datacenters{namespace=~\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client API Error Catalog Datacenter Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent receives an RPC error for a request to list datacenters.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_api_error_catalog_datacenters{namespace=~\"$namespace\", service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client API Catalog Nodes Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent receives a request to list nodes from the catalog.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_api_catalog_nodes{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client API Success Catalog Nodes Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent successfully responds to a request to list nodes.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_api_success_catalog_nodes{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client RPC Error Catalog Nodes Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent receives an RPC error for a request to list nodes.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_rpc_error_catalog_nodes{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client API Catalog Services Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent receives a request to list services from the catalog.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_api_catalog_services{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client API Catalog Success Services Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent successfully responds to a request to list services.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_api_success_catalog_services{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client RPC Error Catalog Services Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent receives an RPC error for a request to list services.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_rpc_error_catalog_services{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client API Catalog Service Nodes Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent receives a request to list nodes offering a service.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_api_catalog_service_nodes{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client API Success Catalog Service Nodes Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent successfully responds to a request to list nodes offering a service.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_api_success_catalog_service_nodes{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client RPC Error Catalog Service Nodes Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent receives an RPC error for a request to list nodes offering a service.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_rpc_error_catalog_service_nodes{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client API Catalog Node Services Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent receives a request to list services registered in a node.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_api_catalog_node_services{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client API Success Catalog Node Services Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent successfully responds to a request to list services in a service.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_api_success_catalog_node_services{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client RPC Error Catalog Node Services Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments whenever a Consul agent receives an RPC error for a request to list services in a service.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_client_rpc_error_catalog_node_services{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client Runtime Num of Go Routines",
   "type": "graph",
   "description": "This tracks the number of running goroutines and is a general load pressure indicator. This may burst from time to time but should return to a steady state value.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consul_runtime_num_goroutines{namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client Runtime Bytes Allocated",
   "type": "graph",
   "description": "This measures the number of bytes allocated by the Consul process. This may burst from time to time but should return to a steady state value.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "consul_runtime_alloc_bytes{namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client Runtime Heap Objects",
   "type": "graph",
   "description": "This measures the number of objects allocated on the heap and is a general memory pressure indicator. This may burst from time to time but should return to a steady state value.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "consul_runtime_heap_objects{namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client ACL Cache Hit Count Rate [ /minute ]",
   "type": "graph",
   "description": "The number of ACL cache hits.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_acl_cache_hit{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client ACL Cache Miss Count Rate [ /minute ]",
   "type": "graph",
   "description": "The number of ACL cache misses.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_acl_cache_miss{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client ACL Replication Hit Count Rate [ /minute ]",
   "type": "graph",
   "description": "The number of ACL replication cache hits (when not running in the ACL datacenter).\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_acl_replication_hit{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client DNS Stale Queries Count Rate [ /minute ]",
   "type": "graph",
   "description": "This increments when an agent serves a query within the allowed stale threshold.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_dns_stale_queries{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client DNS PTR query Count Rate [ /minute ]",
   "type": "graph",
   "description": "This measures the time spent handling a reverse DNS query for the given node.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_dns_ptr_query{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client DNS Domain Query Count Rate [ /minute ]",
   "type": "graph",
   "description": "This measures the time spent handling a domain query for the given node.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(consul_dns_domain_query{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Client consul_http_GET_* Time p50",
   "type": "graph",
   "description": "This tracks how long it takes to service the given HTTP request for the given verb and path. Paths do not include details like service or key names, for these an underscore will be present as a placeholder (eg. consul.http.GET.v1.kv._)\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"consul_http_GET_.*[^count|sum]\",namespace=~\"$namespace\",service=~\"$service\",quantile=\"0.5\"}",
     "legendFormat": "{{ pod }} - {{ __name__ }} - p50"
    }
   ]
  },
  {
   "title": "Client consul_http_GET_* Time p90",
   "type": "graph",
   "description": "This tracks how long it takes to service the given HTTP request for the given verb and path. Paths do not include details like service or key names, for these an underscore will be present as a placeholder (eg. consul.http.GET.v1.kv._)\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"consul_http_GET_.*[^count|sum]\",namespace=~\"$namespace\",service=~\"$service\",quantile=\"0.9\"}",
     "legendFormat": "{{ pod }} - {{ __name__ }} - p50"
    }
   ]
  },
  {
   "title": "Client consul_http_GET_* Time p99",
   "type": "graph",
   "description": "This tracks how long it takes to service the given HTTP request for the given verb and path. Paths do not include details like service or key names, for these an underscore will be present as a placeholder (eg. consul.http.GET.v1.kv._)\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"consul_http_GET_.*[^count|sum]\",namespace=~\"$namespace\",service=~\"$service\",quantile=\"0.99\"}",
     "legendFormat": "{{ pod }} - {{ __name__ }} - p50"
    }
   ]
  }
 ]
}