{
 "title": "PL Go Process Metrics",
 "tags": [
  "go-process",
  "pulse-line"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(pl_service_server_elapsed_ms, namespace)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(pl_service_server_elapsed_ms{namespace=\"$namespace\"}, application)"
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": "label_values(pl_service_server_elapsed_ms{namespace=\"$namespace\", application=\"$application\"}, realm)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(pl_service_server_elapsed_ms{namespace=\"$namespace\", application=\"$application\", realm=\"$realm\"}, region)"
   },
   {
    "name": "az",
    "label": "AZ",
    "query": "label_values(pl_service_server_elapsed_ms{namespace=\"$namespace\", application=\"$application\", realm=\"$realm\", region=\"$region\"}, az)"
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": "label_values(pl_service_server_elapsed_ms{namespace=\"$namespace\", application=\"$application\", realm=\"$realm\", region=\"$region\", az=\"$az\"}, domain)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(pl_service_server_elapsed_ms{namespace=\"$namespace\", application=\"$application\", realm=\"$realm\", region=\"$region\", az=\"$az\", domain=\"$domain\"}, container)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(pl_service_server_elapsed_ms{namespace=\"$namespace\", application=~\"$application\", realm=~\"$realm\", region=~\"$region\", az=~\"$az\", domain=~\"$domain\", container=~\"$container\"}, pod)"
   },
   {
    "name": "method",
    "label": "API",
    "query": "label_values(pl_service_server_elapsed_ms{namespace=\"$namespace\", application=~\"$application\", realm=~\"$realm\", region=~\"$region\", az=~\"$az\", domain=~\"$domain\", container=~\"$container\", pod=~\"$pod\"}, method)"
   }
  ]
 },
 "panels": [
  { "title": "Go Process Metrics", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "content": "\n# Go Process Metrics\n\n\n" },
  {
   "title": "Go process memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "Go process memory deriv",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod\", container=~\"$container\"}[1m])",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod\", container=~\"$container\"}[1m])",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=~\"$namespace\", container=\"$container\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"$namespace\", container=\"$container\", pod=~\"$pod\"}[30s])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=~\"$namespace\", container=\"$container\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=~\"$namespace\", container=\"$container\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "Go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{namespace=~\"$namespace\",container=\"$container\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"$namespace\",container=\"$container\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{namespace=~\"$namespace\",container=\"$container\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{namespace=~\"$namespace\",container=\"$container\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "Go open fds",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=~\"$namespace\",container=\"$container\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go open fds deriv",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{namespace=~\"$namespace\",container=~\"$container\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go Goroutines",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"$namespace\",container=~\"$container\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=~\"$namespace\",container=~\"$container\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: {{quantile}}"
    }
   ]
  }
 ]
}