{
 "title": "PL Application",
 "description": "Pulse Line application dashboard",
 "tags": [
  "application",
  "pulse-line"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "tke",
    "label": "TKE",
    "query": "label_values(node_uname_info, tke_cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\"}, namespace)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\", namespace=~\"$namespace\"}, application)"
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\", namespace=~\"$namespace\",application=~\"$application\"}, realm)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\", namespace=~\"$namespace\",application=~\"$application\",realm=~\"$realm\"}, region)"
   },
   {
    "name": "az",
    "label": "AZ",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\", namespace=~\"$namespace\",application=~\"$application\",realm=~\"$realm\",region=~\"$region\"}, az)"
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\", namespace=~\"$namespace\",application=~\"$application\",realm=~\"$realm\",region=~\"$region\",az=~\"$az\"}, domain)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\", namespace=~\"$namespace\",application=~\"$application\",realm=~\"$realm\",region=~\"$region\",az=~\"$az\",domain=~\"$domain\"}, container)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\", namespace=~\"$namespace\",application=~\"$application\",realm=~\"$realm\",region=~\"$region\",az=~\"$az\",domain=~\"$domain\",container=~\"$container\"}, pod_ip)"
   },
   {
    "name": "api",
    "label": "API",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\", namespace=~\"$namespace\",application=~\"$application\",realm=~\"$realm\",region=~\"$region\",az=~\"$az\",domain=~\"$domain\",container=~\"$container\",pod_ip=~\"$pod\"}, method)"
   }
  ]
 },
 "panels": [
  {
   "title": "GRPC Application Metrics",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "\n# GRPC Application Metrics\n\n\n"
  },
  {
   "title": "API Request Rate Per Second ( 1m Range )",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pl_service_server_elapsed_ms_count{tke_cluster=~\"$tke\",namespace=~\"$namespace\", application=~\"$application\", realm=~\"$realm\", region=~\"$region\", az=~\"$az\", domain=~\"$domain\", container=~\"$container\", pod_ip=~\"$pod\", method=~\"$api\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Availability",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(pl_service_server_code{tke_cluster=~\"$tke\",namespace=~\"$namespace\", application=~\"$application\", realm=~\"$realm\", region=~\"$region\", az=~\"$az\", domain=~\"$domain\", container=\"$container\", pod_ip=~\"$pod\", server_code!=\"Aborted|Internal|Unavailable\"}) by (server_code, method)/sum(pl_service_server_code{tke_cluster=~\"$tke\",namespace=~\"$namespace\", application=~\"$application\", realm=~\"$realm\", region=~\"$region\", az=~\"$az\", domain=~\"$domain\", container=\"$container\", pod_ip=~\"$pod\"}) by (server_code, method) * 100",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Duration Overall",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\",namespace=~\"$namespace\", application=~\"$application\", realm=~\"$realm\", region=~\"$region\", az=~\"$az\", domain=~\"$domain\", container=\"$container\", pod_ip=~\"$pod\", method=~\"$api\"}) by (method, quantile)",
     "legendFormat": "{{method}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "API Duration P50",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\", namespace=~\"$namespace\", application=~\"$application\", realm=~\"$realm\", region=~\"$region\", az=~\"$az\", domain=~\"$domain\", container=\"$container\", pod_ip=~\"$pod\", method=~\"$api\", quantile=~\"0.5\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Duration P90",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\",namespace=~\"$namespace\", application=~\"$application\", realm=~\"$realm\", region=~\"$region\", az=~\"$az\", domain=~\"$domain\", container=\"$container\", pod_ip=~\"$pod\", method=~\"$api\", quantile=~\"0.9\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Duration P99",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\",namespace=~\"$namespace\", application=~\"$application\", realm=~\"$realm\", region=~\"$region\", az=~\"$az\", domain=~\"$domain\", container=\"$container\", pod_ip=~\"$pod\", method=~\"$api\", quantile=~\"0.99\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Duration P99.9",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\",namespace=~\"$namespace\", application=~\"$application\", realm=~\"$realm\", region=~\"$region\", az=~\"$az\", domain=~\"$domain\", container=\"$container\", pod_ip=~\"$pod\", method=~\"$api\", quantile=~\"0.999\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Server Code",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pl_service_server_code{tke_cluster=~\"$tke\",namespace=~\"$namespace\", application=~\"$application\", realm=~\"$realm\", region=~\"$region\", az=~\"$az\", domain=~\"$domain\", container=\"$container\", pod_ip=~\"$pod\"}[1m])) by (server_code, method)",
     "legendFormat": "{{method}}-{{server_code}}"
    }
   ]
  },
  {
   "title": "API Data Transfer In Bytes Per Second ( 1m Range )",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pl_service_server_bytes_transferred_in{tke_cluster=~\"$tke\",namespace=~\"$namespace\", application=~\"$application\", realm=~\"$realm\", region=~\"$region\", az=~\"$az\", domain=~\"$domain\", container=~\"$container\", pod_ip=~\"$pod\", method=~\"$api\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Data Transfer Out Bytes Per Second ( 1m Range )",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pl_service_server_bytes_transferred_out{tke_cluster=~\"$tke\",namespace=~\"$namespace\", application=~\"$application\", realm=~\"$realm\", region=~\"$region\", az=~\"$az\", domain=~\"$domain\", container=~\"$container\", pod_ip=~\"$pod\", method=~\"$api\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}