{
 "title": "PL Container General Dashboard",
 "tags": [
  "tke",
  "general",
  "pulse-line"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "tke",
    "label": "TKE",
    "query": "label_values(node_uname_info, tke_cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\"}, namespace)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}, application)"
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\",namespace=~\"$namespace\",application=~\"$application\"}, realm)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\",namespace=~\"$namespace\",application=~\"$application\",realm=~\"$realm\"}, region)"
   },
   {
    "name": "az",
    "label": "AZ",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\",namespace=~\"$namespace\",application=~\"$application\",realm=~\"$realm\",region=~\"$region\"}, az)"
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\",namespace=~\"$namespace\",application=~\"$application\",realm=~\"$realm\",region=~\"$region\",az=~\"$az\"}, domain)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\",namespace=~\"$namespace\",application=~\"$application\",realm=~\"$realm\",region=~\"$region\",az=~\"$az\",domain=~\"$domain\"}, container)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\",namespace=~\"$namespace\",application=~\"$application\",realm=~\"$realm\",region=~\"$region\",az=~\"$az\",domain=~\"$domain\",container=~\"$container\"}, pod_ip)"
   },
   {
    "name": "api",
    "label": "API",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\", namespace=~\"$namespace\",application=~\"$application\",realm=~\"$realm\",region=~\"$region\",az=~\"$az\",domain=~\"$domain\",container=~\"$container\",pod_ip=~\"$pod\"}, method)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(pl_service_server_elapsed_ms{tke_cluster=~\"$tke\",namespace=~\"$namespace\",application=~\"$application\",realm=~\"$realm\",region=~\"$region\",az=~\"$az\",domain=~\"$domain\",container=~\"$container\"}, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "POD & Container Metrics",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "\n# POD & Container Metrics\n\n\n"
  },
  {
   "title": "POD Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "count(pl_service_server_elapsed_ms{namespace=\"$namespace\", application=~\"$application\", realm=~\"$realm\", region=~\"$region\", az=~\"$az\", domain=~\"$domain\", container=~\"$container\", pod_ip=~\"$pod\"}) by (namespace, pod, realm, region, az, domain, container, pod_ip, node_ip, pod_phase, deployment_by, pod_type, protocol, scheme, service)"
    },
    {
     "expr": "count(kube_pod_container_info{namespace=\"$namespace\", container=~\"$container\", pod_ip=~\"$pod\"}) by (pod, image)"
    }
   ]
  },
  {
   "title": "POD Status - Cluster",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum (kube_pod_container_info{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"$container\", pod=~\"$instance\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (kube_pod_container_status_running{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"$container\", pod=~\"$instance\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum (kube_pod_container_status_terminated{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"$container\", pod=~\"$instance\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum (kube_pod_container_status_waiting{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"$container\", pod=~\"$instance\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  { "title": "CPU Metrics", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 }, "content": "\n# CPU Metrics\n\n\n" },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"$namespace\", image!=\"\", pod=~\"$instance\", container=~\"$container\", container!=\"POD\"}[4m]))",
     "legendFormat": "Current: {{ pod }}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\", pod=\"$instance\", container=~\"$container\"})",
     "legendFormat": "Requested: {{ pod }}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\", pod=\"$instance\", container=~\"$container\"})",
     "legendFormat": "Limit: {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"$container\", pod=~\"$instance\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", container=\"$container\", pod=~\"$instance\"}) by (pod)"
    },
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"$container\", pod=~\"$instance\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", container=\"$container\", pod=~\"$instance\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"$container\", pod=~\"$instance\"}) by (pod)"
    },
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"$container\", pod=~\"$instance\"}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"$container\", pod=~\"$instance\"}) by (pod)"
    }
   ]
  },
  { "title": "Memory Metrics", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 }, "content": "\n# Memory Metrics\n\n\n" },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{job=\"kubelet\", namespace=\"$namespace\", pod=\"$instance\", container=\"$container\", container!=\"POD\"})",
     "legendFormat": "Current: {{ pod }}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\", pod=\"$instance\", container=~\"$container\"})",
     "legendFormat": "Requested: {{ pod }}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\", pod=\"$instance\", container=~\"$container\"})",
     "legendFormat": "Limit: {{ pod }}"
    },
    {
     "expr": "sum by(pod) (container_memory_cache{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$instance\", container=~\"$container\", container!=\"POD\"})",
     "legendFormat": "Cache: {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"$container\", pod=~\"$instance\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",container=\"$container\", pod=~\"$instance\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"$container\", pod=~\"$instance\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",container=\"$container\", pod=~\"$instance\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"$container\", pod=~\"$instance\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"$container\", pod=~\"$instance\"}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\",container=\"$container\", pod=~\"$instance\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"$namespace\",container=\"$container\", pod=~\"$instance\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{namespace=\"$namespace\",container=\"$container\", pod=~\"$instance\"}) by (pod)"
    }
   ]
  },
  { "title": "Network Metrics", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 44 }, "content": "\n# Network Metrics\n\n\n" },
  {
   "title": "Bytes Received by POD",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (irate(container_network_receive_bytes_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$instance\"}[4m])))",
     "legendFormat": "Received: {{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes Transmitted by POD",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (irate(container_network_transmit_bytes_total{job=\"kubelet\",  namespace=\"$namespace\", pod=~\"$instance\"}[4m])))",
     "legendFormat": "Transmitted: {{ pod }}"
    }
   ]
  },
  {
   "title": "Container Flapping Metrics",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 57 },
   "content": "\n# Container Flapping Metrics\n\n\n"
  },
  {
   "title": "Total number of Restarts ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (container) (kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=~\"$instance\", container=~\"$container\"})",
     "legendFormat": "Restarts: {{ container }}"
    }
   ]
  }
 ]
}