{
 "title": "pl-node-filesystem",
 "description": "Pulse Line style PMET dashboards from node_exporter",
 "tags": [
  "Prometheus",
  "node_exporter",
  "pulse-line",
  "filesystem"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "tke",
    "label": "TKE",
    "query": "label_values(node_uname_info{job=~\"$job\"}, tke_cluster)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{tke_cluster=~\"$tke\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "System info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime from /proc/stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System general information",
   "type": "table",
   "description": "Labeled system information as provided by the uname system call.",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{instance=~'$node'}"
    },
    {
     "expr": "node_time_seconds{instance=~'$node'}*1000"
    },
    {
     "expr": "node_entropy_available_bits{instance=~'$node'}-0"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Used Root FS",
   "type": "singlestat",
   "description": "Used Root FS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Filesystem space available",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$node\",job=~\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Available"
    }
   ]
  },
  {
   "title": "File Nodes Free",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "File Nodes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files_free{instance=~\"$node\",job=~\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Free file nodes"
    }
   ]
  },
  {
   "title": "File Descriptor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Files" }
   ],
   "targets": [
    {
     "expr": "node_filefd_maximum{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Max open files"
    },
    {
     "expr": "node_filefd_allocated{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Open files"
    }
   ]
  },
  {
   "title": "File Nodes Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "File Nodes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files{instance=~\"$node\",job=~\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - File nodes total"
    }
   ]
  },
  {
   "title": "Filesystem in ReadOnly",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Read Only" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_readonly{instance=~\"$node\",job=~\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - ReadOnly"
    }
   ]
  }
 ]
}