{
 "title": "pl-node-cpu",
 "description": "Pulse Line style PMET dashboards from node_exporter",
 "tags": [
  "Prometheus",
  "node_exporter",
  "pulse-line"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "System info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime from /proc/stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System general information",
   "type": "table",
   "description": "Labeled system information as provided by the uname system call.",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{instance=~'$node'}"
    },
    {
     "expr": "node_time_seconds{instance=~'$node'}*1000"
    },
    {
     "expr": "node_entropy_available_bits{instance=~'$node'}-0"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU modes",
   "type": "graph",
   "description": "Collected from /proc/stat, /sys/devices/system/cpu/cpu*, /proc/cpuinfo",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "CPU guest",
   "type": "graph",
   "description": "Seconds the cpus spent in guests (VMs) for each mode.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (cpu,mode)(irate(node_cpu_guest_seconds_total{instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "cpu-{{cpu}}-mode-{{mode}}"
    }
   ]
  },
  {
   "title": "CPU throttle",
   "type": "graph",
   "description": "Number of times this cpu core has been throttled.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (core,package)(irate(node_cpu_core_throttles_total{instance=~\"$node\",job=~\"$job\"}[5m]))",
     "legendFormat": "core-{{core}}-pkg-{{package}}"
    }
   ]
  },
  {
   "title": "CPU package throttle",
   "type": "graph",
   "description": "Number of times this cpu package has been throttled.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (package)(irate(node_cpu_package_throttles_total{instance=~\"$node\",job=~\"$job\"}[5m]))",
     "legendFormat": "pkg-{{package}}"
    }
   ]
  }
 ]
}