{
 "title": "pl-node-network",
 "description": "Pulse Line style PMET dashboards from node_exporter",
 "tags": [
  "Prometheus",
  "node_exporter",
  "pulse-line",
  "network"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   },
   {
    "name": "nic",
    "label": "nic",
    "query": "label_values(node_network_device_id{instance=\"$node\",device!~\"veth.*\"},device)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "System info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime from /proc/stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System general information",
   "type": "table",
   "description": "Labeled system information as provided by the uname system call.",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{instance=~'$node'}"
    },
    {
     "expr": "node_time_seconds{instance=~'$node'}*1000"
    },
    {
     "expr": "node_entropy_available_bits{instance=~'$node'}-0"
    }
   ]
  },
  {
   "title": "System network devices",
   "type": "table",
   "description": "Network devices except for Hyper-V eth",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_network_device_id{instance=~'$node',device!~\"veth.*\"}"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  },
  {
   "title": "Network Traffic Compressed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_compressed_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Receive compressed"
    },
    {
     "expr": "irate(node_network_transmit_compressed_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Transmit compressed"
    }
   ]
  },
  {
   "title": "Network Traffic Frame",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_frame_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Receive frame"
    }
   ]
  },
  {
   "title": "Network Traffic Fifo",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_fifo_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Receive fifo"
    },
    {
     "expr": "irate(node_network_transmit_fifo_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Transmit fifo"
    }
   ]
  },
  {
   "title": "Network Traffic Multicast",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_multicast_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Receive multicast"
    }
   ]
  },
  {
   "title": "Network Traffic Carrier",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_carrier_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Statistic transmit_carrier"
    }
   ]
  },
  {
   "title": "Network Traffic Colls",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_colls_total{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Transmit colls"
    }
   ]
  },
  {
   "title": "NF Contrack",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "NF conntrack entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "NF conntrack limit"
    }
   ]
  },
  {
   "title": "ARP Entries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_arp_entries{instance=~\"$node\",job=~\"$job\",device=~\"$nic\"}",
     "legendFormat": "{{ device }} - ARP entries"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sockstat TCP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "TCP_alloc - Allocated sockets"
      },
      {
       "expr": "node_sockstat_TCP_inuse{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "TCP_inuse - Tcp sockets currently in use"
      },
      {
       "expr": "node_sockstat_TCP_mem{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "TCP_mem - Used memory for tcp"
      },
      {
       "expr": "node_sockstat_TCP_orphan{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "TCP_orphan - Orphan sockets"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "TCP_tw - Sockets wating close"
      }
     ]
    },
    {
     "title": "Sockstat UDP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_UDPLITE_inuse{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "UDPLITE_inuse - Udplite sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_inuse{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "UDP_inuse - Udp sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_mem{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "UDP_mem - Used memory for udp"
      }
     ]
    },
    {
     "title": "Sockstat Used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_sockets_used{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Sockets_used - Sockets currently in use"
      }
     ]
    },
    {
     "title": "Sockstat Memory Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_mem_bytes{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "TCP_mem_bytes - "
      },
      {
       "expr": "node_sockstat_UDP_mem_bytes{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "UDP_mem_bytes - "
      }
     ]
    },
    {
     "title": "Sockstat FRAG / RAW",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_FRAG_inuse{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "FRAG_inuse - Frag sockets currently in use"
      },
      {
       "expr": "node_sockstat_FRAG_memory{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "FRAG_memory - Used memory for frag"
      },
      {
       "expr": "node_sockstat_RAW_inuse{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "RAW_inuse - Raw sockets currently in use"
      }
     ]
    }
   ]
  },
  {
   "title": "Netstat IP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Netstat IP In / Out Octets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Octects out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_IpExt_InOctets{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InOctets - Received octets"
      },
      {
       "expr": "irate(node_netstat_IpExt_OutOctets{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutOctets - Sent octets"
      }
     ]
    },
    {
     "title": "Netstat IP Forwarding",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Datagrams" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Ip_ForwDatagrams{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "ForwDatagrams - IP outforwdatagrams"
      },
      {
       "expr": "irate(node_netstat_Ip_Forwarding{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Forwarding - IP forwarding"
      }
     ]
    }
   ]
  },
  {
   "title": "Netstat TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Segments",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Segments out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_InCsumErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InCsumErrors - Segments received with checksum errors"
      },
      {
       "expr": "irate(node_netstat_Tcp_InErrs{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
      },
      {
       "expr": "irate(node_netstat_Tcp_InSegs{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutRsts{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutRsts - Segments sent containing the RST flag"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutSegs{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
      },
      {
       "expr": "node_netstat_Tcp_MaxConn{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dinamic is \"-1\")"
      }
     ]
    },
    {
     "title": "TCP Direct Transition",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
      },
      {
       "expr": "irate(node_netstat_Tcp_AttemptFails{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "AttemptFails - TCP connections that have made a direct transition to the CLOSED state from either the SYN-SENT and SYN-RCVD"
      },
      {
       "expr": "irate(node_netstat_Tcp_EstabResets{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "EstabResets - TCP connections that have made a direct transition to the CLOSED state from either the ESTABLISHED state or the CLOSE-WAIT state"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
      }
     ]
    },
    {
     "title": "TCP SynCookie / Challenge",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Counter out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
      },
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "SyncookiesRecv - SYN cookies received"
      },
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "SyncookiesSent - SYN cookies sent"
      }
     ]
    },
    {
     "title": "TCP DROPS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
      }
     ]
    },
    {
     "title": "TCP Issues",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
      }
     ]
    }
   ]
  },
  {
   "title": "Netstat UDP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "UDP In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InDatagrams - Datagrams received"
      },
      {
       "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutDatagrams - Datagrams sent"
      }
     ]
    },
    {
     "title": "UDP Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InCsumErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InCsumErrors - Datagrams with checksum errors"
      },
      {
       "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InErrors - Datagrams that could not be delivered to an application"
      },
      {
       "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "RcvbufErrors - Datagrams for which not enough socket buffer memory to receive"
      },
      {
       "expr": "irate(node_netstat_Udp_SndbufErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "SndbufErrors - Datagrams for which not enough socket buffer memory to transmit"
      },
      {
       "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "NoPorts - Datagrams received on a port with no listener"
      }
     ]
    },
    {
     "title": "UDP Lite In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_UdpLite_InDatagrams{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InDatagrams - Packets received"
      },
      {
       "expr": "irate(node_netstat_UdpLite_OutDatagrams{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutDatagrams - Packets sent"
      }
     ]
    },
    {
     "title": "UDP Lite Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_UdpLite_InCsumErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InCsumErrors - Datagrams with checksum errors"
      },
      {
       "expr": "irate(node_netstat_UdpLite_InErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InErrors - Datagrams that could not be delivered to an application"
      },
      {
       "expr": "irate(node_netstat_UdpLite_RcvbufErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "RcvbufErrors - Datagrams for which not enough socket buffer memory to receive"
      },
      {
       "expr": "irate(node_netstat_UdpLite_SndbufErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "SndbufErrors - Datagrams for which not enough socket buffer memory to transmit"
      },
      {
       "expr": "irate(node_netstat_UdpLite_NoPorts{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "NoPorts - Datagrams received on a port with no listener"
      }
     ]
    }
   ]
  },
  {
   "title": "Netstat ICMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "ICMP Errors 1",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutErrors - Messages which this entity did not send due to problems discovered within ICMP, such as a lack of buffers"
      },
      {
       "expr": "irate(node_netstat_Icmp_InDestUnreachs{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InDestUnreachs - Destination Unreachable messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutDestUnreachs{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutDestUnreachs - Destination Unreachable messages sent"
      },
      {
       "expr": "irate(node_netstat_IcmpMsg_InType3{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InType3 - Destination unreachable"
      },
      {
       "expr": "irate(node_netstat_IcmpMsg_OutType3{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutType3 - Destination unreachable"
      },
      {
       "expr": "irate(node_netstat_IcmpMsg_InType11{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InType11 - Time Exceeded"
      }
     ]
    },
    {
     "title": "ICMP Errors 2",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InCsumErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InCsumErrors - Messages with ICMP checksum errors"
      },
      {
       "expr": "irate(node_netstat_Icmp_InTimeExcds{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InTimeExcds - Time Exceeded messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutTimeExcds{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutTimeExcds - Time Exceeded messages sent"
      },
      {
       "expr": "irate(node_netstat_Icmp_InParmProbs{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InParmProbs - Parameter Problem messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutParmProbs{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutParmProb - Parameter Problem messages sent"
      },
      {
       "expr": "irate(node_netstat_Icmp_InSrcQuenchs{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InSrcQuenchs - Source Quench messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutSrcQuenchs{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutSrcQuenchs - Source Quench messages sent"
      }
     ]
    },
    {
     "title": "ICMP In / Out - Messages / Redirects",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InMsgs{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
      },
      {
       "expr": "irate(node_netstat_Icmp_InRedirects{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InRedirects - Redirect messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutMsgs{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutRedirects{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutRedirects -  Redirect messages sent. For a host, this object will always be zero, since hosts do not send redirects"
      }
     ]
    },
    {
     "title": "ICMP Timestamps",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InTimestampReps{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InTimestampReps - Timestamp Reply messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_InTimestamps{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InTimestamps - Timestamp (request) messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutTimestampReps{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutTimestampReps - Timestamp Reply messages sent"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutTimestamps{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutTimestamps - Timestamp (request) messages sent"
      }
     ]
    },
    {
     "title": "ICMP Echos",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InEchoReps{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InEchoReps - Echo Reply messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_InEchos{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InEchos - Echo (request) messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutEchoReps{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutEchoReps - Echo Reply messages sent"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutEchos{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutEchos - Echo (request) messages sent"
      }
     ]
    },
    {
     "title": "ICMP Masks",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InAddrMaskReps{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InAddrMaskReps - Address Mask Reply messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_InAddrMasks{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InAddrMasks - Address Mask Request messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutAddrMaskReps{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutAddrMaskReps - Address Mask Reply messages sent"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutAddrMasks{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutAddrMasks - Address Mask Request messages sent"
      }
     ]
    }
   ]
  }
 ]
}