{
 "title": "pl-node-disk",
 "description": "Pulse Line style PMET dashboards from node_exporter",
 "tags": [
  "Prometheus",
  "node_exporter",
  "pulse-line",
  "disk"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "System info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime from /proc/stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System general information",
   "type": "table",
   "description": "Labeled system information as provided by the uname system call.",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{instance=~'$node'}"
    },
    {
     "expr": "node_time_seconds{instance=~'$node'}*1000"
    },
    {
     "expr": "node_entropy_available_bits{instance=~'$node'}-0"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Used Root FS",
   "type": "singlestat",
   "description": "Used Root FS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",job=~\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=~\"$node\",job=~\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\",job=~\"$job\",device=~\"[a-z]*[a-z]\"} [5m])",
     "legendFormat": "{{device}} - Time spent doing I/Os"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "Disk R/W Time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "s", "label": "Time. read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Read time"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Write time"
    }
   ]
  },
  {
   "title": "Disk IOs Weighted",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - IO time weighted"
    }
   ]
  },
  {
   "title": "Disk R/W Merged",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "iops", "label": "I/Os" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_merged_total{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Read merged"
    },
    {
     "expr": "irate(node_disk_writes_merged_total{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Write merged"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - IO time"
    }
   ]
  },
  {
   "title": "Disk IOs Current in Progress",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "iops", "label": "I/Os" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_now{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - IO now"
    }
   ]
  },
  {
   "title": "Open Error File",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "node_textfile_scrape_error{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Textfile scrape error (1 = true)"
    }
   ]
  }
 ]
}