{
 "title": "pl-node-memory",
 "description": "Pulse Line style PMET dashboards from node_exporter",
 "tags": [
  "Prometheus",
  "node_exporter",
  "pulse-line",
  "memory"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "tke",
    "label": "TKE",
    "query": "label_values(node_uname_info{job=~\"$job\"}, tke_cluster)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{tke_cluster=~\"$tke\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "System info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime from /proc/stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System general information",
   "type": "table",
   "description": "Labeled system information as provided by the uname system call.",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{instance=~'$node'}"
    },
    {
     "expr": "node_time_seconds{instance=~'$node'}*1000"
    },
    {
     "expr": "node_entropy_available_bits{instance=~'$node'}-0"
    }
   ]
  },
  { "title": "Memory basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"} - (node_memory_Cached_bytes{instance=~\"$node\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_Buffers_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_Cached_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_Slab_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_PageTables_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_SwapCached_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Unused - Free memory unasigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  { "title": "Memory Detail Meminfo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory Active / Inactive",
   "type": "graph",
   "description": "Collected from /proc/meminfo\t",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Inactive_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
    },
    {
     "expr": "node_memory_Active_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
    }
   ]
  },
  {
   "title": "Memory Commited",
   "type": "graph",
   "description": "Collected from /proc/meminfo",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
    },
    {
     "expr": "node_memory_CommitLimit_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "CommitLimit - Amount of  memory currently available to be allocated on the system"
    }
   ]
  },
  {
   "title": "Memory Active / Inactive Detail",
   "type": "graph",
   "description": "Collected from /proc/meminfo",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Inactive_file_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Inactive_file - File-backed memory on inactive LRU list"
    },
    {
     "expr": "node_memory_Inactive_anon_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Inactive_anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)"
    },
    {
     "expr": "node_memory_Active_file_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Active_file - File-backed memory on active LRU list"
    },
    {
     "expr": "node_memory_Active_anon_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Active_anon - Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs"
    }
   ]
  },
  {
   "title": "Memory Writeback and Dirty",
   "type": "graph",
   "description": "Collected from /proc/meminfo",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Writeback_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Writeback - Memory which is actively being written back to disk"
    },
    {
     "expr": "node_memory_WritebackTmp_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
    },
    {
     "expr": "node_memory_Dirty_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
    }
   ]
  },
  {
   "title": "Memory Shared and Mapped",
   "type": "graph",
   "description": "Collected from /proc/meminfo",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Mapped_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Mapped - Used memory in mapped pages files which have been mmaped, such as libraries"
    },
    {
     "expr": "node_memory_Shmem_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Shmem - Used shared memory (shared between several processes, thus including RAM disks)"
    }
   ]
  },
  {
   "title": "Memory Slab",
   "type": "graph",
   "description": "Collected from /proc/meminfo",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SUnreclaim_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "SUnreclaim - Part of Slab, that cannot be reclaimed on memory pressure"
    },
    {
     "expr": "node_memory_SReclaimable_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "SReclaimable - Part of Slab, that might be reclaimed, such as caches"
    }
   ]
  },
  {
   "title": "Memory Vmalloc",
   "type": "graph",
   "description": "Collected from /proc/meminfo",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_VmallocChunk_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "VmallocChunk - Largest contigious block of vmalloc area which is free"
    },
    {
     "expr": "node_memory_VmallocTotal_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "VmallocTotal - Total size of vmalloc memory area"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "VmallocUsed - Amount of vmalloc area which is used"
    }
   ]
  },
  {
   "title": "Memory Bounce",
   "type": "graph",
   "description": "Collected from /proc/meminfo",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Bounce_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Bounce - Memory used for block device bounce buffers"
    }
   ]
  },
  {
   "title": "Memory Anonymous",
   "type": "graph",
   "description": "Collected from /proc/meminfo",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_AnonHugePages_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "AnonHugePages - Memory in anonymous huge pages"
    },
    {
     "expr": "node_memory_AnonPages_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "AnonPages - Memory in user pages not backed by files"
    }
   ]
  },
  {
   "title": "Memory Kernel",
   "type": "graph",
   "description": "Collected from /proc/meminfo",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_KernelStack_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "KernelStack - Kernel memory stack. This is not reclaimable"
    }
   ]
  },
  {
   "title": "Memory HugePages Counter",
   "type": "graph",
   "description": "Collected from /proc/meminfo",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Pages" }
   ],
   "targets": [
    {
     "expr": "node_memory_HugePages_Free{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "HugePages_Free - Huge pages in the pool that are not yet allocated"
    },
    {
     "expr": "node_memory_HugePages_Rsvd{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "HugePages_Rsvd - Huge pages for which a commitment to allocate from the pool has been made, but no allocation has yet been made"
    },
    {
     "expr": "node_memory_HugePages_Surp{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "HugePages_Surp - Huge pages in the pool above the value in /proc/sys/vm/nr_hugepages"
    }
   ]
  },
  {
   "title": "Memory HugePages Size",
   "type": "graph",
   "description": "Collected from /proc/meminfo",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_HugePages_Total{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "HugePages - Total size of the pool of huge pages"
    },
    {
     "expr": "node_memory_Hugepagesize_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Hugepagesize - Huge Page size"
    }
   ]
  },
  {
   "title": "Memory DirectMap",
   "type": "graph",
   "description": "Collected from /proc/meminfo",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_DirectMap1G{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "DirectMap1G - Amount of pages mapped as this size"
    },
    {
     "expr": "node_memory_DirectMap2M_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "DirectMap2M - Amount of pages mapped as this size"
    },
    {
     "expr": "node_memory_DirectMap4k_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "DirectMap4K - Amount of pages mapped as this size"
    }
   ]
  },
  {
   "title": "Memory Unevictable and MLocked",
   "type": "graph",
   "description": "Collected from /proc/meminfo",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Unevictable_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Unevictable - Amount of unevictable memory that can't be swapped out for a variety of reasons"
    },
    {
     "expr": "node_memory_Mlocked_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "MLocked - Size of pages locked to memory using the mlock() system call"
    }
   ]
  },
  {
   "title": "Memory NFS",
   "type": "graph",
   "description": "Collected from /proc/meminfo",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_NFS_Unstable_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "NFS Unstable - Memory in NFS pages sent to the server, but not yet commited to the storage"
    }
   ]
  },
  {
   "title": "Memory  Detail VMStat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pages In / Out",
     "type": "graph",
     "description": "Collected from  /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "short", "label": "Pages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgpgin{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pagesin - Page in operations"
      },
      {
       "expr": "irate(node_vmstat_pgpgout{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pagesout - Page out operations"
      }
     ]
    },
    {
     "title": "Memory Pages Swap In / Out",
     "type": "graph",
     "description": "Collected from  /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 108 },
     "yaxes": [
      { "format": "short", "label": "Pages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pswpin{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pswpin - Pages swapped in"
      },
      {
       "expr": "irate(node_vmstat_pswpout{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pswpout - Pages swapped out"
      }
     ]
    },
    {
     "title": "Memory Page Operations",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgdeactivate{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgdeactivate - Pages moved from active to inactive"
      },
      {
       "expr": "irate(node_vmstat_pgfree{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgfree - Page free operations"
      },
      {
       "expr": "irate(node_vmstat_pgactivate{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgactivate - Pages moved from inactive to active"
      }
     ]
    },
    {
     "title": "Memory Page Faults",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 118 },
     "yaxes": [
      { "format": "short", "label": "Faults" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgfault{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgfault - Page major and minor fault operations"
      },
      {
       "expr": "irate(node_vmstat_pgmajfault{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgmajfault - Major page fault operations"
      },
      {
       "expr": "irate(node_vmstat_pgfault{instance=~\"$node\",job=~\"$job\"}[5m])  - irate(node_vmstat_pgmajfault{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgminfault - Minor page fault operations"
      }
     ]
    },
    {
     "title": "Memory Pages Reclaimed",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 128 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_kswapd_inodesteal{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Kswapd_inodesteal - Pages reclaimed via kswapd inode freeing"
      },
      {
       "expr": "irate(node_vmstat_pginodesteal{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgindesteal - Pages reclaimed via inode freeing"
      }
     ]
    },
    {
     "title": "Memory Calls Reclaimed",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 128 },
     "yaxes": [
      { "format": "short", "label": "Calls" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pageoutrun{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pageoutrun - Kswapd calls to page reclaim"
      },
      {
       "expr": "irate(node_vmstat_allocstall{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Allocstall - Direct reclaim calls"
      },
      {
       "expr": "irate(node_vmstat_zone_reclaim_failed{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Zone_reclaim_failed - Zone reclaim failures"
      }
     ]
    },
    {
     "title": "Memory Page Rotate",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 138 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgrotated{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgrotated - Pages rotated to tail of the LRU"
      }
     ]
    },
    {
     "title": "Memory Page Drop",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 138 },
     "yaxes": [
      { "format": "short", "label": "Calls" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_drop_pagecache{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Drop_pagecache - Calls to drop page cache pages"
      },
      {
       "expr": "node_vmstat_drop_slab{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Drop_slab - Calls to drop slab cache pages"
      }
     ]
    },
    {
     "title": "Memory Scan Slab",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 148 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_slabs_scanned{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Slabs_scanned - Slab pages scanned"
      }
     ]
    },
    {
     "title": "Memory Unevictable Pages",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 148 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_unevictable_pgs_cleared{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Unevictable_pgs_cleared - Unevictable pages cleared"
      },
      {
       "expr": "irate(node_vmstat_unevictable_pgs_culled{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Unevictable_pgs_culled - Unevictable pages culled"
      },
      {
       "expr": "irate(node_vmstat_unevictable_pgs_mlocked{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Unevictable_pgs_mlocked - Unevictable pages mlocked"
      },
      {
       "expr": "irate(node_vmstat_unevictable_pgs_munlocked{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Unevictable_pgs_munlocked - Unevictable pages munlocked"
      },
      {
       "expr": "irate(node_vmstat_unevictable_pgs_rescued{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Unevictable_pgs_rescued- Unevictable pages rescued"
      },
      {
       "expr": "irate(node_vmstat_unevictable_pgs_scanned{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Unevictable_pgs_scanned - Unevictable pages scanned"
      },
      {
       "expr": "irate(node_vmstat_unevictable_pgs_stranded{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "unevictable_pgs_stranded - Unevictable pages stranded"
      }
     ]
    },
    {
     "title": "Memory Page Allocation",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 158 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgalloc_dma{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgalloc_dma - Dma mem page allocations"
      },
      {
       "expr": "irate(node_vmstat_pgalloc_dma32{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgalloc_dma32 - Dma32 mem page allocations"
      },
      {
       "expr": "irate(node_vmstat_pgalloc_movable{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgalloc_movable - Movable mem page allocations"
      },
      {
       "expr": "irate(node_vmstat_pgalloc_normal{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgalloc_normal - Normal mem page allocations"
      }
     ]
    },
    {
     "title": "Memory Page Refill",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 158 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgrefill_dma{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgrefill_dma - Dma mem pages inspected in refill_inactive_zone"
      },
      {
       "expr": "irate(node_vmstat_pgrefill_dma32{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgrefill_dma32 - Dma32 mem pages inspected in refill_inactive_zone"
      },
      {
       "expr": "irate(node_vmstat_pgrefill_movable{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgrefill_movable - Movable mem pages inspected in refill_inactive_zone"
      },
      {
       "expr": "irate(node_vmstat_pgrefill_normal{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgrefill_normal - Normal mem pages inspected in refill_inactive_zone"
      }
     ]
    },
    {
     "title": "Memory Scan Direct",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 168 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgscan_direct_dma{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgscan_direct_dma - Dma mem pages scanned"
      },
      {
       "expr": "irate(node_vmstat_pgscan_direct_dma32{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgscan_direct_dma32 - Dma32 mem pages scanned"
      },
      {
       "expr": "irate(node_vmstat_pgscan_direct_movable{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgscan_direct_movable - Movable mem pages scanned"
      },
      {
       "expr": "irate(node_vmstat_pgscan_direct_normal{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgscan_direct_normal - Normal mem pages scanned"
      }
     ]
    },
    {
     "title": "Memory Scan Kswapd",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 168 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgscan_kswapd_dma{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgscan_kswapd_dma - Dma mem pages scanned by kswapd"
      },
      {
       "expr": "irate(node_vmstat_pgscan_kswapd_dma32{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgscan_kswapd_dma32 - Dma32 mem pages scanned by kswapd"
      },
      {
       "expr": "irate(node_vmstat_pgscan_kswapd_movable{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgscan_kswapd_movable - Movable mem pages scanned by kswapd"
      },
      {
       "expr": "irate(node_vmstat_pgscan_kswapd_normal{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgscan_kswapd_normal - Normal mem pages scanned by kswapd"
      }
     ]
    },
    {
     "title": "Memory Page Compact",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 178 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_compact_free_scanned{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Compact_free_scanned - Pages scanned for freeing by compaction daemon"
      },
      {
       "expr": "irate(node_vmstat_compact_isolated{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Compact_isolated - Page isolations for memory compaction"
      },
      {
       "expr": "irate(node_vmstat_compact_migrate_scanned{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Compact_migrate_scanned - Pages scanned for migration by compaction daemon"
      }
     ]
    },
    {
     "title": "Memory Compactions",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 178 },
     "yaxes": [
      { "format": "short", "label": "Compactions" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_compact_fail{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Compact_fail - Unsuccessful compactions for high order allocations"
      },
      {
       "expr": "irate(node_vmstat_compact_stall{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Compact_stall - Failures to even start compacting"
      },
      {
       "expr": "irate(node_vmstat_compact_success{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Compact_sucess - Successful compactions for high order allocations"
      }
     ]
    },
    {
     "title": "Memory Kswapd Watermark",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 188 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_kswapd_high_wmark_hit_quickly{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Kswapd_high_wmark_hit_quickly - Times high watermark reached quickly"
      },
      {
       "expr": "node_vmstat_kswapd_low_wmark_hit_quickly{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Kswapd_low_wmark_hit_quickly - Times low watermark reached quickly"
      }
     ]
    },
    {
     "title": "Memory Buddy Alloc",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 188 },
     "yaxes": [
      { "format": "short", "label": "Allocations" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_htlb_buddy_alloc_fail{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Htlb_buddy_alloc_fail - Huge TLB page buddy allocation failures"
      },
      {
       "expr": "node_vmstat_htlb_buddy_alloc_success{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Htlb_buddy_alloc_success - Huge TLB page buddy allocation successes"
      }
     ]
    },
    {
     "title": "Memory Numa Allocations",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 198 },
     "yaxes": [
      { "format": "short", "label": "Allocations" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_numa_foreign{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Numa_foreign - Foreign NUMA zone allocations"
      },
      {
       "expr": "irate(node_vmstat_numa_hit{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Numa_hit - Successful allocations from preferred NUMA zone"
      },
      {
       "expr": "irate(node_vmstat_numa_interleave{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Numa_interleave - Interleaved NUMA allocations in each zone for each NUMA node"
      },
      {
       "expr": "irate(node_vmstat_numa_local{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Numa_local - Successful allocations from local NUMA zone"
      },
      {
       "expr": "irate(node_vmstat_numa_miss{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Numa_miss - Unsuccessful allocations from preferred NUMA zona"
      },
      {
       "expr": "irate(node_vmstat_numa_other{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Numa_other - Unsuccessful allocations from local NUMA zone"
      }
     ]
    },
    {
     "title": "Memory Numa Page Migrations",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 198 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_numa_pages_migrated{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Numa_pages_migrated - NUMA page migrations"
      },
      {
       "expr": "irate(node_vmstat_pgmigrate_fail{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgmigrate_fail - Unsuccessful NUMA page migrations"
      },
      {
       "expr": "irate(node_vmstat_pgmigrate_success{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgmigrate_success - Successful NUMA page migrations"
      }
     ]
    },
    {
     "title": "Memory Numa Hints",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 208 },
     "yaxes": [
      { "format": "short", "label": "HInts" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_numa_hint_faults{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Numa_hint_faults - NUMA hint faults trapped"
      },
      {
       "expr": "irate(node_vmstat_numa_hint_faults_local{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Numa_hint_faults_local - Hinting faults to local nodes"
      }
     ]
    },
    {
     "title": "Memory Numa Table Updates",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 208 },
     "yaxes": [
      { "format": "short", "label": "Updates" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_numa_pte_updates{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Numa_pte_updates - NUMA page table entry updates"
      },
      {
       "expr": "irate(node_vmstat_numa_huge_pte_updates{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Numa_huge_pte_updates - NUMA huge page table entry updates"
      }
     ]
    },
    {
     "title": "Memory THP Splits",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 218 },
     "yaxes": [
      { "format": "short", "label": "Splits" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_thp_split{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Thp_split - Transparent huge page splits"
      }
     ]
    },
    {
     "title": "Memory Workingset",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 218 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_workingset_activate{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Workingset_activate - Page activations to form the working set"
      },
      {
       "expr": "irate(node_vmstat_workingset_nodereclaim{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Workingset_nodereclaim - NUMA node working set page reclaims"
      },
      {
       "expr": "irate(node_vmstat_workingset_refault{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Workingset_refault - Refaults of previously evicted pages"
      }
     ]
    },
    {
     "title": "Memory THP Allocations",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 228 },
     "yaxes": [
      { "format": "short", "label": "Allocations" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_thp_collapse_alloc{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Thp_collapse_alloc - Transparent huge page collapse allocations"
      },
      {
       "expr": "irate(node_vmstat_thp_collapse_alloc_failed{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Thp_collapse_alloc_failed - Transparent huge page collapse allocation failures"
      },
      {
       "expr": "irate(node_vmstat_thp_zero_page_alloc{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Thp_zero_page_alloc - Transparent huge page zeroed page allocations"
      },
      {
       "expr": "irate(node_vmstat_thp_zero_page_alloc_failed{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Thp_zero_page_alloc_failed - Transparent huge page zeroed page allocation failures"
      },
      {
       "expr": "irate(node_vmstat_thp_fault_alloc{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Thp_fault_alloc - Transparent huge page fault allocations"
      },
      {
       "expr": "irate(node_vmstat_thp_fault_fallback{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Thp_fault_fallback - Transparent huge page fault fallbacks"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Detail VMStat Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Page Active",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_active_anon{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Active_anon - Active anonymous memory pages"
      },
      {
       "expr": "node_vmstat_nr_active_file{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Active_file - Active file memory memory pages"
      }
     ]
    },
    {
     "title": "Memory Page Inactive",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 109 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_inactive_anon{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Inactive_anon - Inactive anonymous memory pages in each zone for each NUMA node"
      },
      {
       "expr": "node_vmstat_nr_inactive_file{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Inactive_file - Inactive file memory pages in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Reclaimed / Unreclaimed",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 119 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_slab_reclaimable{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Reclaimable - Instantaneous reclaimable slab pages"
      },
      {
       "expr": "node_vmstat_nr_slab_unreclaimable{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Unreclaimable - Instantaneous unreclaimable slab pages"
      }
     ]
    },
    {
     "title": "Memory Page Free / Written",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 119 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_free_pages{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Free_pages - Free pages"
      },
      {
       "expr": "node_vmstat_nr_written{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Written - Pages written out in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Dirty / Bounce",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 129 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_dirty{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Dirty - Pages in dirty state"
      },
      {
       "expr": "node_vmstat_nr_bounce{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Bounce - Bounce buffer pages"
      }
     ]
    },
    {
     "title": "Memory Pages Unevictable / Mlock",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 129 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_unevictable{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Unevictable - Unevictable pages"
      },
      {
       "expr": "node_vmstat_nr_mlock{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Mlock - Pages under mlock"
      }
     ]
    },
    {
     "title": "Memory Page Shmem / Mapped",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 139 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_shmem{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Shmem - Shared memory pages"
      },
      {
       "expr": "node_vmstat_nr_mapped{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Mapped - Mapped pagecache pages in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Kernel_stack",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 139 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_kernel_stack{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Kernel_stack - Pages of kernel stack"
      }
     ]
    },
    {
     "title": "Memory Pages Writeback",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 149 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_writeback{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Writeback - Writeback pages"
      },
      {
       "expr": "node_vmstat_nr_writeback_temp{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Writeback_temp - Temporary writeback pages"
      }
     ]
    },
    {
     "title": "Memory Page File_pages",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 149 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_file_pages{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "File_pages - File pagecache pages in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Dirty Threshold",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 159 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_dirty_background_threshold{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Dirty_background_threshold - Background writeback threshold"
      },
      {
       "expr": "node_vmstat_nr_dirty_threshold{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Dirty_threshold - Dirty throttling threshold"
      }
     ]
    },
    {
     "title": "Memory Page Unstable / Dirtied",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 159 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_unstable{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Unstable - Pages unstable state in each zone for each NUMA node"
      },
      {
       "expr": "node_vmstat_nr_dirtied{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Dirtied - Pages entering dirty state in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Page_table_pages",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 169 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_page_table_pages{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Page_table_pages - Page table pages in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Alloc_batch",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 169 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_alloc_batch{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Alloc_batch - Pages allocated to other zones due to insufficient memory for each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Isolated",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 179 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_isolated_anon{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Isolated_anon - Isolated anonymous memory pages in each zone for each NUMA node"
      },
      {
       "expr": "node_vmstat_nr_isolated_file{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Isolated_file - Isolated file memory pages in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Anon",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 179 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_anon_pages{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Anon_pages - Anonymous mapped pagecache pages in each zone for each NUMA node"
      },
      {
       "expr": "node_vmstat_nr_anon_transparent_hugepages{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Anon_transparent_hugepages - Anonymous transparent huge pages in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Misc",
     "type": "graph",
     "description": "Collected from /proc/vmstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 189 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_free_cma{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Free_cma - Free Contiguous Memory Allocator pages in each zone for each NUMA node"
      },
      {
       "expr": "node_vmstat_nr_vmscan_write{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Vmscan_write - Pages written by VM scanner from LRU"
      },
      {
       "expr": "node_vmstat_nr_vmscan_immediate_reclaim{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Immediate_reclaim - Prioritise for reclaim when writeback ends in each zone for each NUMA node"
      }
     ]
    }
   ]
  }
 ]
}