{
 "title": "K8S-Workloads-Daemonset",
 "description": "Kubernetes workloads for statefulset",
 "tags": [
  "pulse-line",
  "kubernetes",
  "statefulset",
  "workloads"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "tke",
    "label": "TKE",
    "query": "label_values(node_uname_info{}, tke_cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{tke_cluster=~\"$tke\"}, namespace)"
   },
   {
    "name": "daemonset",
    "label": "Daemonset",
    "query": "label_values(mixin_pod_workload{tke_cluster=~\"$tke\",namespace=~\"$namespace\",workload_type=~\"daemonset\"}, workload)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\", pod_name=~\"$daemonset-.*\", container_name!=\"POD\", container_name!=\"POD\"}, container_name)"
   }
  ]
 },
 "panels": [
  { "title": "Application Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daemonsets status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{namespace=~\"$namespace\", daemonset=~\"$daemonset\"}",
     "legendFormat": "Available - {{daemonset}}"
    },
    {
     "expr": "kube_daemonset_status_number_unavailable{namespace=~\"$namespace\", daemonset=~\"$daemonset\"}",
     "legendFormat": "Unavailable - {{daemonset}}"
    }
   ]
  },
  {
   "title": "Daemonsets status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{tke_cluster=~\"$tke\",namespace=~\"$namespace\", daemonset=~\"$daemonset\"}",
     "legendFormat": "Available - {{daemonset}}"
    },
    {
     "expr": "kube_daemonset_status_number_unavailable{tke_cluster=~\"$tke\",namespace=~\"$namespace\", daemonset=~\"$daemonset\"}",
     "legendFormat": "Unavailable - {{daemonset}}"
    }
   ]
  },
  {
   "title": "Containers' statuses",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\"}",
     "legendFormat": "Ready -  {{pod}} - {{container}}"
    },
    {
     "expr": "kube_pod_container_status_running{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\"}",
     "legendFormat": "Running -  {{pod}} - {{container}}"
    },
    {
     "expr": "kube_pod_container_status_waiting{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\"}",
     "legendFormat": "Waiting -  {{pod}} - {{container}}"
    },
    {
     "expr": "kube_pod_container_status_terminated{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\"}",
     "legendFormat": "Terminated -  {{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "Containers' restarts total",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Containers' restarts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\"}",
     "legendFormat": "Restarts - {{pod}} - {{ container}}"
    }
   ]
  },
  { "title": "Application Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod_name=~\"$daemonset-.*\", container_name=~\"$container\"}[2m])) by (pod_name)",
     "legendFormat": "Used: {{pod_name}} - {$container}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container_name=~\"$container\"}",
     "legendFormat": "Requested: {{pod}} - {$container}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod_name=~\"$daemonset-.*\", container_name!=\"\", container_name!=\"POD\", container_name=~\"$container\"}) by (pod_name)",
     "legendFormat": "Used: {{pod_name}} - {$container}"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{ tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\"}) by (pod)",
     "legendFormat": "Requested: {{pod}} - {$container}"
    }
   ]
  },
  {
   "title": "Traffic transmit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod_name=~\"$daemonset-.*\"}[2m])",
     "legendFormat": "{{interface}} : {{pod_name}}"
    }
   ]
  },
  {
   "title": "Traffic receive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod_name=~\"$daemonset-.*\"}[2m])",
     "legendFormat": "{{interface}} : {{pod_name}}"
    }
   ]
  }
 ]
}