{
 "title": "TKE-Cluster",
 "description": "Summary metrics about Kubernentes Cluster (Tencent Cloud)",
 "tags": [
  "kubernetes",
  "pulse-line",
  "tke"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "tke",
    "label": "TKE",
    "query": "label_values(node_uname_info, tke_cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{tke_cluster=~\"$tke\"}, namespace)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Pod Usage",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) / sum(kube_node_status_allocatable_pods{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{tke_cluster=~\"$tke\",mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{tke_cluster=~\"$tke\"})"
    }
   ]
  },
  {
   "title": "Total Disk",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{tke_cluster=~\"$tke\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) / sum(kube_node_status_allocatable_cpu_cores{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{tke_cluseter=~\"$tke\",namespace=~\"$namespace\"}) / sum(kube_node_status_allocatable_memory_bytes{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) - sum (node_filesystem_free_bytes{tke_cluster=~\"$tke\",namespace=~\"$namespace\"})) / sum (node_filesystem_size_bytes{tke_cluster=~\"$tke\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "kube_node_info{tke_cluster=~\"$tke\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mixin_pod_workload{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_info{tke_cluster=~\"$tke\"}) - sum(kube_node_spec_unschedulable{tke_cluster=~\"$tke\"})",
     "legendFormat": "Healthy"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{tke_cluster=~\"$tke\"})",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_info{tke_cluster=~\"$tke\"})",
     "legendFormat": "Healthy"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{tke_cluster=~\"$tke\"})",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mixin_pod_workload{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (workload_type)",
     "legendFormat": "{{workload_type}}"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mixin_pod_workload{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (workload_type)",
     "legendFormat": "{{workload_type}}"
    }
   ]
  },
  {
   "title": "Workloads by namespace",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mixin_pod_workload{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Workloads by namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mixin_pod_workload{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 56 }, "content": "# Pods" },
  {
   "title": "Pods Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", tke_cluster=~\"$tke\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\",tke_cluster=~\"$tke\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 68 }, "content": "# Containers" },
  {
   "title": "Container Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{tke_cluster=~\"$tke\",namespace=~\"$namespace\"})",
     "legendFormat": "terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_running{tke_cluster=~\"$tke\",namespace=~\"$namespace\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{tke_cluster=~\"$tke\",namespace=~\"$namespace\"})",
     "legendFormat": "waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_{tke_cluster=~\"$tke\",namespace=~\"$namespace\"})",
     "legendFormat": "waiting"
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{tke_cluster=~\"$tke\",namespace=~\"$namespace\"})",
     "legendFormat": "terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_ready{tke_cluster=~\"$tke\",namespace=~\"$namespace\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{tke_cluster=~\"$tke\",namespace=~\"$namespace\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{tke_cluster=~\"$tke\",namespace=~\"$namespace\"})",
     "legendFormat": "waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_{tke_cluster=~\"$tke\",namespace=~\"$namespace\"})",
     "legendFormat": "waiting"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 80 }, "content": "# Services & Ingress" },
  {
   "title": "Service",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_service_info{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_service_info{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_ingress_info{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_ingress_info{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 102 }, "content": "# Cluster Resource" },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(mixin_pod_workload{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "count(avg(mixin_pod_workload{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace) / sum(kube_pod_container_resource_requests_cpu_cores{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace) / sum(kube_pod_container_resource_limits_cpu_cores{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{tke_cluster=~\"$tke\", namespace=~\"$namespace\",container!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{tke_cluster=~\"$tke\", namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{tke_cluster=~\"$tke\", namespace=~\"$namespace\",container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{tke_cluster=~\"$tke\", namespace=~\"$namespace\"}) by (namespaced)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{tke_cluster=~\"$tke\", namespace=~\"$namespace\",container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{tke_cluster=~\"$tke\", namespace=~\"$namespace\",container!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_cache{tke_cluster=~\"$tke\", namespace=~\"$namespace\",container!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_swap{tke_cluster=~\"$tke\", namespace=~\"$namespace\",container!=\"\"}) by (namespace)"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Deployment Replicas",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 113 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{tke_cluster=~\"$tke\",namespace=~\"$namespace\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{tke_cluster=~\"$tke\",namespace=~\"$namespace\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 113 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{tke_cluster=~\"$tke\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  }
 ]
}