{
 "title": "TKE-Workloads-Statefulset",
 "tags": [
  "pulse-line",
  "kubernetes",
  "statefulset",
  "workloads"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "tke",
    "label": "TKE",
    "query": "label_values(node_uname_info{}, tke_cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{tke_cluster=~\"$tke\"}, namespace)"
   },
   {
    "name": "statefulset",
    "label": "Statefulset",
    "query": "label_values(mixin_pod_workload{tke_cluster=~\"$tke\",namespace=~\"$namespace\",workload_type=~\"statefulset\"}, workload)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\", pod_name=~\"$statefulset-.*\", container_name!=\"POD\", container_name!=\"POD\"}, container_name)"
   }
  ]
 },
 "panels": [
  { "title": "Application Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Statefulset status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas{namespace=~\"$namespace\", statefulset=~\"$statefulset\"}",
     "legendFormat": "created - {{statefulset}}"
    },
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\", statefulset=~\"$statefulset\"}",
     "legendFormat": "ready - {{statefulset}}"
    },
    {
     "expr": "kube_statefulset_status_replicas_current{namespace=~\"$namespace\", statefulset=~\"$statefulset\"}",
     "legendFormat": "current - {{statefulset}}"
    },
    {
     "expr": "kube_statefulset_status_replicas_updated{namespace=~\"$namespace\", statefulset=~\"$statefulset\"}",
     "legendFormat": "updated - {{statefulset}}"
    }
   ]
  },
  {
   "title": "Containers' statuses",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=~\"$namespace\", pod=~\"$statefulset-.*\", container=~\"$container\"}",
     "legendFormat": "Ready {{pod}}-{{container}}"
    },
    {
     "expr": "kube_pod_container_status_running{namespace=~\"$namespace\", pod=~\"$statefulset-.*\", container=~\"$container\"}",
     "legendFormat": "Running  {{pod}}-{{container}}"
    },
    {
     "expr": "kube_pod_container_status_waiting{namespace=~\"$namespace\", pod=~\"$statefulset-.*\", container=~\"$container\"}",
     "legendFormat": "Waiting  {{pod}}-{{container}}"
    },
    {
     "expr": "kube_pod_container_status_terminated{namespace=~\"$namespace\", pod=~\"$statefulset-.*\", container=~\"$container\"}",
     "legendFormat": "Terminated  {{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "Containers' restarts total",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$statefulset-.*\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Containers' restarts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$statefulset-.*\", container=~\"$container\"}",
     "legendFormat": " {{pod}}-{{container}}"
    }
   ]
  },
  { "title": "Application Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod_name=~\"$statefulset-.*\", container_name=~\"$container\"}[2m])) by (pod_name)",
     "legendFormat": "Used: {{pod_name}} "
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$statefulset-.*\", container_name=~\"$container\"}) by (pod)",
     "legendFormat": "Requested: {{pod}} "
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod_name=~\"$statefulset-.*\", container_name!=\"\", container_name!=\"POD\", container_name=~\"$container\"}) by (pod_name)",
     "legendFormat": "Used: {{pod_name}}"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$statefulset-.*\", container=~\"$container\"}) by (pod)",
     "legendFormat": "Requested: {{pod}}"
    }
   ]
  },
  {
   "title": "Traffic transmit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{tke_cluster=~\"$tke\",namespace=\"$namespace\", pod_name=~\"$statefulset-.*\"}[2m])",
     "legendFormat": "{{interface}} : [{{pod_name}}]"
    }
   ]
  },
  {
   "title": "Traffic receive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{tke_cluster=~\"$tke\",namespace=\"$namespace\", pod_name=~\"$statefulset-.*\"}[2m])",
     "legendFormat": "{{interface}} : [{{pod_name}}]"
    }
   ]
  }
 ]
}